services:
  nginx:
    image: nginx:latest
    container_name: monetriq_nginx
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - app
    restart: always
